# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed9efa4373e85936b19a8952b0d34a7d8eec93c61c8016cbd9a58898524a36f71b0052084686ce54da30ead8b40f1cbbf670686b8ecd57c3f0ff4d9ddaafdc4b

test:
  secret_key_base: 98d74b70141ab4a2184548e593df5a5979c9a80a7c98e9d242a04f482f2d85cd405a8b3d998bdb4d62f0a24846bb73edc4be04297ffb61f1f884b4fe3a48a04f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
